import pandas as pd
import numpy as np
from datetime import timedelta
from sklearn.preprocessing import MinMaxScaler, StandardScaler
# Or use custom time-based split logic if needed
from sklearn.model_selection import train_test_split

# --- Configuration ---
# Directory containing synthetic CSVs generated by other scripts
DATA_DIR = './data'
# Placeholder for MIMIC-IV data path (if used)
MIMIC_DIR = '/path/to/mimic/data'
# Placeholder for Synthea data path (if used)
SYNTHEA_DIR = '/path/to/synthea/data'
# Placeholder for external weather data file
WEATHER_FILE = '/path/to/weather/boston_weather.csv'
# Flags to control data source (currently uses synthetic generators)
USE_MIMIC = False
USE_SYNTHEA = False
# Prediction target lag (predict migraine 1 day ahead)
TARGET_LAG_DAYS = 1
# Example dates for time-based train/validation/test splits
TIME_SPLIT_DATE_VALID = '2024-05-01'
TIME_SPLIT_DATE_TEST = '2024-06-01'

# --- Loading Functions ---
def load_synthetic_data(data_dir):
    """Loads data from CSV files generated by the synthetic generators."""
    try:
        profiles = pd.read_csv(f"{data_dir}/patient_profiles.csv")
        sleep = pd.read_csv(f"{data_dir}/sleep_data.csv", parse_dates=['date'])
        # Assuming weather_data.csv is generated or an external file is placed here
        weather = pd.read_csv(f"{data_dir}/weather_data.csv", parse_dates=['date'])
        stress_diet = pd.read_csv(f"{data_dir}/stress_diet_data.csv", parse_dates=['date'])
        migraine_events = pd.read_csv(f"{data_dir}/migraine_events.csv", parse_dates=['date'])
        print("Successfully loaded synthetic data CSVs.")
        # TODO: Add loading for external weather if weather_data.csv is not generated
        return profiles, sleep, weather, stress_diet, migraine_events
    except FileNotFoundError as e:
        print(f"Error loading synthetic data: {e}. Make sure generator scripts have run and CSVs are in {data_dir}")
        raise

def load_mimic_data(mimic_dir):
    """Placeholder function to load relevant MIMIC-IV tables."""
    # Example: Load patients, admissions, chartevents, labevents, diagnoses_icd, prescriptions
    print(f"Loading MIMIC-IV data from {mimic_dir} (Placeholder)...")
    # patients = pd.read_csv(f"{mimic_dir}/hosp/patients.csv.gz")
    # admissions = pd.read_csv(f"{mimic_dir}/hosp/admissions.csv.gz")
    # chartevents = pd.read_csv(f"{mimic_dir}/icu/chartevents.csv.gz", nrows=100000) # Load sample for structure
    # ... load other necessary tables ...
    print("MIMIC-IV loading placeholder complete.")
    # Return dictionary of loaded dataframes
    return {} # Return empty dict for now

def load_synthea_data(synthea_dir):
    """Placeholder function to load relevant Synthea tables."""
    # Example: Load patients.csv, conditions.csv, observations.csv, procedures.csv, medications.csv
    print(f"Loading Synthea data from {synthea_dir} (Placeholder)...")
    # patients = pd.read_csv(f"{synthea_dir}/patients.csv")
    # conditions = pd.read_csv(f"{synthea_dir}/conditions.csv")
    # ... load other necessary tables ...
    print("Synthea loading placeholder complete.")
    # Return dictionary of loaded dataframes
    return {} # Return empty dict for now

# --- Preprocessing Functions ---
def preprocess_physio(mimic_data=None, synthea_data=None):
    """Placeholder for preprocessing physiological data from MIMIC/Synthea."""
    print("Preprocessing Physio data (Placeholder)...")
    if not mimic_data and not synthea_data:
        print("Skipping Physio preprocessing: No MIMIC or Synthea data provided.")
        return None # Return None if no EHR data
    # --- Placeholder Logic ---
    # 1. Select relevant patients/admissions.
    # 2. Filter chartevents, labevents, prescriptions etc. for the cohort.
    # 3. Aggregate time-series data (vitals, labs) to daily level (mean, min, max, std).
    # 4. Engineer features (e.g., flags for abnormal values, rolling averages).
    # 5. Handle missing values (imputation, forward/backward fill).
    # 6. Normalize features.
    # 7. Return dataframe indexed by patient_id and date.
    # Example structure:
    # physio_features = pd.DataFrame(index=pd.MultiIndex.from_tuples([], names=['patient_id', 'date']))
    # physio_features['daily_avg_hr'] = ...
    # physio_features['max_temp'] = ...
    # physio_features['lab_x_value'] = ...
    print("Physio preprocessing placeholder complete.")
    return None # Return None for now

def preprocess_sleep(sleep_df):
    """Preprocesses sleep data (from synthetic generator)."""
    print("Preprocessing Sleep data...")
    sleep_df = sleep_df.set_index(['patient_id', 'date'])
    # Normalize continuous features using MinMaxScaler
    scaler = MinMaxScaler()
    cols_to_scale = ['total_sleep_hours', 'deep_sleep_pct', 'rem_sleep_pct', 'light_sleep_pct', 'awake_time_mins', 'sleep_quality']
    # Check if columns exist before scaling
    valid_cols = [col for col in cols_to_scale if col in sleep_df.columns]
    if valid_cols:
        sleep_df[valid_cols] = scaler.fit_transform(sleep_df[valid_cols])
        print(f"Normalized sleep columns: {valid_cols}")
        return sleep_df[valid_cols]
    else:
        print("Warning: No sleep columns found to scale.")
        return pd.DataFrame(index=sleep_df.index) # Return empty df with index

def preprocess_weather(weather_df):
    """Preprocesses weather data (from synthetic generator or external)."""
    print("Preprocessing Weather data...")
    # If weather data is external, it might only have 'date'. Need to merge it onto patient-date index later.
    if 'patient_id' in weather_df.columns:
        weather_df = weather_df.set_index(['patient_id', 'date'])
    else:
        weather_df = weather_df.set_index('date') # Assume external source

    scaler = MinMaxScaler()
    cols_to_scale = ['temperature', 'humidity', 'pressure', 'pressure_change_24h']
    valid_cols = [col for col in cols_to_scale if col in weather_df.columns]
    if valid_cols:
        weather_df[valid_cols] = scaler.fit_transform(weather_df[valid_cols])
        print(f"Normalized weather columns: {valid_cols}")
        return weather_df[valid_cols]
    else:
        print("Warning: No weather columns found to scale.")
        return pd.DataFrame(index=weather_df.index)

def preprocess_stress_diet(stress_diet_df):
    """Preprocesses stress and diet data (from synthetic generator)."""
    print("Preprocessing Stress/Diet data...")
    stress_diet_df = stress_diet_df.set_index(['patient_id', 'date'])
    # Normalize continuous features
    scaler = MinMaxScaler()
    cols_to_scale = ['stress_level', 'water_consumed_liters']
    valid_cols_cont = [col for col in cols_to_scale if col in stress_diet_df.columns]
    if valid_cols_cont:
        stress_diet_df[valid_cols_cont] = scaler.fit_transform(stress_diet_df[valid_cols_cont])
        print(f"Normalized stress/diet columns: {valid_cols_cont}")

    # Convert boolean flags to int (0 or 1)
    bool_cols = ['alcohol_consumed', 'caffeine_consumed', 'chocolate_consumed', 'processed_food_consumed']
    valid_cols_bool = [col for col in bool_cols if col in stress_diet_df.columns]
    if valid_cols_bool:
        stress_diet_df[valid_cols_bool] = stress_diet_df[valid_cols_bool].astype(int)
        print(f"Converted boolean stress/diet columns to int: {valid_cols_bool}")

    feature_cols = valid_cols_cont + valid_cols_bool
    if feature_cols:
        return stress_diet_df[feature_cols]
    else:
        print("Warning: No stress/diet columns found.")
        return pd.DataFrame(index=stress_diet_df.index)

# --- Target Variable Function ---
def create_target(migraine_events_df, all_dates_index, target_lag_days):
    """Creates the target variable (migraine next day) aligned to the full patient-date index."""
    print(f"Creating target variable (migraine {target_lag_days} day(s) ahead)...")
    target_df = pd.DataFrame(index=all_dates_index)

    # Map migraine events to the full index
    migraine_events_df = migraine_events_df.set_index(['patient_id', 'date'])
    # Ensure 'has_migraine' column exists, default to False if not found in the file
    if 'has_migraine' not in migraine_events_df.columns:
         # If only positive events are logged, create the boolean flag
         print("\'has_migraine\' column not found in migraine_events.csv. Assuming rows indicate a migraine.")
         migraine_events_df['has_migraine'] = True

    target_df['has_migraine_today'] = migraine_events_df['has_migraine'].reindex(target_df.index, fill_value=False).astype(bool)

    # Create lagged target for prediction
    target_df['target_migraine_lagged'] = target_df.groupby(level='patient_id')['has_migraine_today'].shift(-target_lag_days)

    # Drop rows where target is NaN (due to lag at the end of each patient's series)
    target_df = target_df.dropna(subset=['target_migraine_lagged'])
    target_df['target_migraine_lagged'] = target_df['target_migraine_lagged'].astype(int)
    print(f"Target variable created. Shape: {target_df.shape}")
    return target_df[['target_migraine_lagged']]

# --- Main Processing Logic ---
def process_data():
    """Orchestrates the loading, preprocessing, merging, and splitting of data."""
    # 1. Load Data
    # Currently loads only synthetic data
    profiles, sleep_raw, weather_raw, stress_diet_raw, migraine_events_raw = load_synthetic_data(DATA_DIR)

    mimic_data = load_mimic_data(MIMIC_DIR) if USE_MIMIC else None
    synthea_data = load_synthea_data(SYNTHEA_DIR) if USE_SYNTHEA else None

    # 2. Preprocess Modalities
    sleep_features = preprocess_sleep(sleep_raw)
    weather_features = preprocess_weather(weather_raw)
    stress_diet_features = preprocess_stress_diet(stress_diet_raw)
    physio_features = preprocess_physio(mimic_data, synthea_data)

    # 3. Create a common patient-date index covering the full range
    all_patient_ids = profiles['patient_id'].unique()
    # Determine date range from available data (e.g., sleep data)
    if not sleep_raw.empty:
        min_date = sleep_raw['date'].min()
        max_date = sleep_raw['date'].max()
    else: # Fallback if sleep data is missing
        min_date = pd.to_datetime('2024-01-01')
        max_date = min_date + timedelta(days=179) # Default to 180 days
    date_range = pd.date_range(start=min_date, end=max_date, freq='D')
    master_index = pd.MultiIndex.from_product([all_patient_ids, date_range], names=['patient_id', 'date'])
    print(f"Created master index with {len(master_index)} patient-date entries.")

    # 4. Create Target Variable aligned to master index
    target = create_target(migraine_events_raw, master_index, TARGET_LAG_DAYS)

    # 5. Merge Features
    # Reindex features to the master index, handling potential mismatches
    feature_list = []
    if sleep_features is not None and not sleep_features.empty:
        feature_list.append(sleep_features.reindex(master_index))
    if weather_features is not None and not weather_features.empty:
        # Handle weather indexed only by date (external source)
        if 'patient_id' not in weather_features.index.names:
             weather_features = weather_features.reindex(date_range)
             # Need to broadcast weather features to all patients for each date
             weather_full = pd.DataFrame(index=master_index)
             for col in weather_features.columns:
                 weather_full[col] = weather_features[col].reindex(master_index.get_level_values('date')).values
             feature_list.append(weather_full)
        else:
             feature_list.append(weather_features.reindex(master_index))
    if stress_diet_features is not None and not stress_diet_features.empty:
        feature_list.append(stress_diet_features.reindex(master_index))
    if physio_features is not None and not physio_features.empty:
        feature_list.append(physio_features.reindex(master_index))

    if not feature_list:
        raise ValueError("No features could be processed. Check data loading and preprocessing steps.")

    all_features = pd.concat(feature_list, axis=1)
    print(f"Merged features shape: {all_features.shape}")

    # 6. Combine Features and Target
    # Inner join ensures we only keep rows where target is available (handles the lag)
    final_data = all_features.join(target, how='inner')
    print(f"Final data shape after joining target: {final_data.shape}")

    # 7. Add Static Features (Optional)
    # Example: Add age and sex from profiles
    profiles_indexed = profiles.set_index('patient_id')
    if 'age' in profiles_indexed.columns:
        final_data['age'] = final_data.index.get_level_values('patient_id').map(profiles_indexed['age'])
        # Normalize age
        final_data['age'] = MinMaxScaler().fit_transform(final_data[['age']])
    if 'sex' in profiles_indexed.columns:
        # One-hot encode sex
        final_data = pd.get_dummies(final_data, columns=['sex'], prefix='sex', drop_first=True)
    print("Added static features (age, sex encoding).")

    # 8. Handle Remaining Missing Data (Post-Merge/Reindex)
    # Use forward fill then backward fill as a simple strategy
    initial_nan_count = final_data.isna().sum().sum()
    if initial_nan_count > 0:
        print(f"Handling {initial_nan_count} remaining NaN values using ffill/bfill...")
        final_data = final_data.fillna(method='ffill').fillna(method='bfill')
        # Fill any remaining NaNs (e.g., if a patient has no data at all) with 0
        final_data = final_data.fillna(0)
        print("NaN handling complete.")
    else:
        print("No remaining NaN values found after merging.")

    # 9. Data Splitting (Time-based)
    print(f"Splitting data using validation date '{TIME_SPLIT_DATE_VALID}' and test date '{TIME_SPLIT_DATE_TEST}'...")
    train_data = final_data[final_data.index.get_level_values('date') < TIME_SPLIT_DATE_VALID]
    valid_data = final_data[(final_data.index.get_level_values('date') >= TIME_SPLIT_DATE_VALID) &
                            (final_data.index.get_level_values('date') < TIME_SPLIT_DATE_TEST)]
    test_data = final_data[final_data.index.get_level_values('date') >= TIME_SPLIT_DATE_TEST]

    # 10. Final Structuring for FuseMoE (Separate X and y)
    target_col = 'target_migraine_lagged'
    feature_cols = [col for col in final_data.columns if col != target_col]

    X_train, y_train = train_data[feature_cols], train_data[target_col]
    X_valid, y_valid = valid_data[feature_cols], valid_data[target_col]
    X_test, y_test = test_data[feature_cols], test_data[target_col]

    print(f"Data shapes: Train X={X_train.shape}, y={y_train.shape}")
    print(f"Data shapes: Valid X={X_valid.shape}, y={y_valid.shape}")
    print(f"Data shapes: Test X={X_test.shape}, y={y_test.shape}")

    # Ensure no NaN in final outputs
    assert not X_train.isna().any().any(), "NaNs found in X_train"
    assert not X_valid.isna().any().any(), "NaNs found in X_valid"
    assert not X_test.isna().any().any(), "NaNs found in X_test"

    # Return processed data splits
    return X_train, y_train, X_valid, y_valid, X_test, y_test

if __name__ == "__main__":
    print("Starting data processing pipeline...")
    try:
        X_train, y_train, X_valid, y_valid, X_test, y_test = process_data()
        print("Data processing pipeline completed successfully.")
        # Example: Save processed data
        # X_train.to_parquet('./processed_data/X_train.parquet')
        # y_train.to_csv('./processed_data/y_train.csv')
        # ... etc ...
    except Exception as e:
        print(f"An error occurred during data processing: {e}")
        import traceback
        traceback.print_exc()

