
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="Data Visualization",
    page_icon="📊",
    layout="wide"
)

st.title("Data Visualization")

st.markdown('''
This page provides visualizations of the enhanced synthetic data generated by the pipeline.
The data includes sleep patterns, weather conditions, stress/diet factors, and physiological measurements.
''')

# Generate mock data for visualization
np.random.seed(42)
num_samples = 100
dates = pd.date_range(start='2025-01-01', periods=num_samples)

# Sleep data
sleep_data = pd.DataFrame({
    'Date': dates,
    'Sleep Duration': np.random.normal(7, 1, num_samples),
    'Sleep Quality': np.random.normal(0.7, 0.15, num_samples),
    'REM Sleep': np.random.normal(0.25, 0.05, num_samples),
    'Deep Sleep': np.random.normal(0.3, 0.07, num_samples)
})

# Weather data
weather_data = pd.DataFrame({
    'Date': dates,
    'Temperature': np.random.normal(20, 5, num_samples),
    'Humidity': np.random.normal(0.6, 0.1, num_samples),
    'Pressure': np.random.normal(1013, 5, num_samples),
    'Precipitation': np.random.exponential(0.5, num_samples)
})

# Stress/Diet data
stress_diet_data = pd.DataFrame({
    'Date': dates,
    'Stress Level': np.random.normal(0.5, 0.2, num_samples),
    'Caffeine Intake': np.random.exponential(2, num_samples),
    'Alcohol Intake': np.random.exponential(1, num_samples),
    'Meal Regularity': np.random.normal(0.7, 0.15, num_samples)
})

# Physiological data
physio_data = pd.DataFrame({
    'Date': dates,
    'Heart Rate': np.random.normal(70, 8, num_samples),
    'Blood Pressure': np.random.normal(120, 10, num_samples),
    'Cortisol Level': np.random.normal(15, 3, num_samples),
    'Body Temperature': np.random.normal(36.8, 0.3, num_samples)
})

# Target data (migraine occurrence)
target_data = pd.DataFrame({
    'Date': dates,
    'Migraine': np.random.binomial(1, 0.2, num_samples)
})

# Display data distributions
st.header("Data Distributions")

tab1, tab2, tab3, tab4, tab5 = st.tabs(["Sleep", "Weather", "Stress/Diet", "Physiological", "Target"])

with tab1:
    st.subheader("Sleep Data Distribution")
    st.line_chart(sleep_data.set_index('Date')[['Sleep Duration', 'Sleep Quality']])
    
with tab2:
    st.subheader("Weather Data Distribution")
    st.line_chart(weather_data.set_index('Date')[['Temperature', 'Humidity']])
    
with tab3:
    st.subheader("Stress/Diet Data Distribution")
    st.line_chart(stress_diet_data.set_index('Date')[['Stress Level', 'Caffeine Intake']])
    
with tab4:
    st.subheader("Physiological Data Distribution")
    st.line_chart(physio_data.set_index('Date')[['Heart Rate', 'Blood Pressure']])
    
with tab5:
    st.subheader("Migraine Occurrence")
    st.bar_chart(target_data.set_index('Date')['Migraine'])

# Display correlations
st.header("Correlations Between Variables")

# Combine all data
combined_data = pd.DataFrame({
    'Sleep Duration': sleep_data['Sleep Duration'],
    'Sleep Quality': sleep_data['Sleep Quality'],
    'Temperature': weather_data['Temperature'],
    'Humidity': weather_data['Humidity'],
    'Stress Level': stress_diet_data['Stress Level'],
    'Caffeine Intake': stress_diet_data['Caffeine Intake'],
    'Heart Rate': physio_data['Heart Rate'],
    'Blood Pressure': physio_data['Blood Pressure'],
    'Migraine': target_data['Migraine']
})

# Display correlation matrix
st.dataframe(combined_data.corr().style.background_gradient(cmap='coolwarm'))

# Raw data explorer
st.header("Raw Data Explorer")

data_type = st.selectbox("Select Data Type", ["Sleep", "Weather", "Stress/Diet", "Physiological", "Target"])

if data_type == "Sleep":
    st.dataframe(sleep_data)
elif data_type == "Weather":
    st.dataframe(weather_data)
elif data_type == "Stress/Diet":
    st.dataframe(stress_diet_data)
elif data_type == "Physiological":
    st.dataframe(physio_data)
else:
    st.dataframe(target_data)
